name = "Newtrinos"
uuid = "5b289081-bab5-45e8-97fc-86872f1653a0"
authors = ["Philipp Eller"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
