name: Run Global Fit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.11'

    - name: Install project dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Run Julia script
      run: |
        julia --project=. src/analysis/analysis.jl --experiments dayabay minos --task profile --name test --ordering NO --plot

    - name: Upload output
      uses: actions/upload-artifact@v4
      with:
        name: newtrinos-output
        path: |
          test.png
          test.jld2
